### PR TITLE
Create zh_CN.lang

### PR DESCRIPTION
**Pull request by Joccob**
Is that possible to translate the text in the GUI?  It doesn't looks like in the .lang file.

ps: I like modular system, great mod.

### CODE REVIEW

**Comment by pauljoda** [comment]
Yeah localization is on my list. I'm going to go through and add references to everything. I'll go ahead and leave this open until then and I'll let you update it at that point. Thanks a lot for the help

**Comment by Dyonovan** [comment]
Code is currently being completely rewritten.

**Comment by Joccob** [comment]
Yeah, I check your MCF post. Actually I am quite excited about the new version. Really looking forward to it, Feel free to give me a message and let me do the translation once you are done.

**Comment by pauljoda** [comment]
I've been doing my best to keep all text in the language file, this mod will be ongoing for quite some time so feel free to drop and and translate some stuff whenever or after large releases. There is a lot more text in this version because I've kept it all separate so be prepared

**Pull request closed without merging**
